Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

1.Logistic Regression

2.SVM

3.Decision Tree

4.Random Forest

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [6]:
X_train

array([[5.4, 3.9, 1.7, 0.4],
       [7.4, 2.8, 6.1, 1.9],
       [4.6, 3.1, 1.5, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [5.4, 3.4, 1.5, 0.4],
       [5. , 3.5, 1.3, 0.3],
       [5.6, 3. , 4.1, 1.3],
       [6.4, 2.8, 5.6, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [4.8, 3.4, 1.6, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.7, 3.3, 5.7, 2.5],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [5.6, 2.9, 3.6, 1.3],
       [7.7, 3.8, 6.7, 2.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [6.2, 2.2, 4.5, 1.5],
       [5.1, 3.7, 1.5, 0.4],
       [5.9, 3. , 5.1, 1.8],
       [5. , 3.3, 1.4, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.9, 3.6, 1.4, 0.1],
       [6.9, 3.2, 5.7, 2.3],
       [5.7, 2.9, 4.2, 1.3],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.1],
       [6.7, 3

In [9]:
len(X_train)

105

In [7]:
X_test

array([[5.4, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.5, 3.9, 1.1],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5.2, 3.5, 1.5, 0.2],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [6.4, 2.9, 4.3, 1.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [4.9, 3.1, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.3, 4.4, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [5.1, 3.5, 1.4, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [4.7, 3.2, 1.3, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.8, 2.7, 4.1, 1. ],
       [7.7, 2.8, 6.7, 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.6, 2.9, 4.6, 1.3],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.6, 4. , 1.2],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 3. , 5.5, 2.1],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [5.1, 2

In [10]:
len(X_test)

45

In [11]:
y_train

array([0, 2, 0, 2, 2, 2, 1, 0, 0, 1, 2, 1, 0, 2, 2, 2, 2, 1, 1, 1, 1, 2,
       0, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 1, 0, 0, 2,
       1, 2, 0, 0, 0, 0, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 0, 1, 0, 1, 0,
       2, 0, 2, 2, 0, 0, 2, 1, 2, 2, 1, 1, 0, 0, 1, 2, 0])

In [12]:
y_test

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1,
       2, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 2, 1, 1, 0, 2, 1, 0, 1, 2, 2, 2,
       2])

In [13]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9777777777777777

In [15]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9555555555555556

In [17]:
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
tree.score(X_test, y_test)

0.9555555555555556

In [19]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9555555555555556

In [20]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [21]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [25]:
get_score(LogisticRegression(), X_train , X_test, y_train, y_test)

0.9777777777777777

In [26]:
get_score(SVC(), X_train , X_test, y_train, y_test)

0.9555555555555556

In [27]:
get_score(DecisionTreeClassifier(), X_train , X_test, y_train, y_test)

0.9555555555555556

In [28]:
get_score(RandomForestClassifier(), X_train , X_test, y_train, y_test)

0.9555555555555556

In [29]:
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)

C:\Users\meraj\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [35]:
cross_val_score(SVC(), iris.data, iris.target,cv=3)

array([0.96, 0.98, 0.94])

In [36]:
cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.98])

In [37]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.96])

In [38]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), iris.data, iris.target, cv=3)
np.average(scores1)

0.96

In [39]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), iris.data, iris.target, cv=3)
np.average(scores2)

0.9466666666666667

In [40]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)
np.average(scores3)

0.96

In [41]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=100), iris.data, iris.target, cv=3)
np.average(scores4)

0.9666666666666667